spring:
    application:
        name: msapigateway
    zipkin:
        baseUrl: ${ZIPKIN-URL:http://localhost:9411}
server:
    port: ${SERVER-PORT:8091}
    contextPath: /  
eureka:
  instance:
    hostname: ${SERVER-HOST:0.0.0.0}
  client:
    preferSameZoneEureka: true
    registerWithEureka: true
    fetchRegistry: true
    region: ${REGION:east}
    preferSameZoneEureka: true 
    serviceUrl:
      defaultZone: http://${EUREKA-SERVER1-HOST:0.0.0.0}:${EUREKA-SERVER1-PORT:8761}/eureka,http://${EUREKA-SERVER2-HOST:0.0.0.0}:${EUREKA-SERVER2-PORT:8762}/eureka 
zuul:
  #Service will be mapped under http://localhost:8091/api-gateway/mls/getDecision1
  prefix: /api-gateway
  routes:
    mlservice:
      path: /mls/**
      serviceId: mlservice
      stripPrefix: true      
ribbon:
    eureka:
        enabled: true
        MaxAutoRetries: 0
        MaxAutoRetriesNextServer: 1
        ReadTimeout: 10000
        PoolMaxThreads: 500
        MaxTotalConnections: 500
        MaxConnectionsPerHost: 50
        MaxHttpConnectionsPerHost: 50
        MaxTotalHttpConnections: 500
